# Generated by Django 2.0.5 on 2018-08-03 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0002_vocentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
