# Generated by Django 2.0.5 on 2018-08-03 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcards', '0003_auto_20180803_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_size', models.IntegerField()),
                ('mode', models.CharField(max_length=4)),
                ('voc_freq', models.IntegerField()),
                ('punitive_rhn', models.IntegerField()),
                ('initial_rhn', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
