# Generated by Django 2.0.5 on 2018-09-09 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcards', '0004_fcsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('secret', models.BooleanField()),
                ('language', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='fcards.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vocentry',
            name='lft_lemma',
        ),
        migrations.RemoveField(
            model_name='vocentry',
            name='rgt_lemma',
        ),
        migrations.AddField(
            model_name='vocentry',
            name='lft_lemma_ID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='lft_lemma_display',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='lft_usage_ID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='rgt_lemma_ID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='rgt_lemma_display',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='rgt_usage_ID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fcards.Language'),
        ),
        migrations.AddField(
            model_name='vocentry',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fcards.Project'),
        ),
    ]
