# Generated by Django 2.0.5 on 2018-09-10 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0005_auto_20180909_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcsettings',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='fcards.Project'),
        ),
    ]
