# Generated by Django 2.0.5 on 2019-03-01 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcards', '0006_fcsettings_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingWindowIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fw', to='fcards.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fw', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
