# Generated by Django 2.0.5 on 2019-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0008_auto_20190303_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcsettings',
            name='extract_sentences',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
