# Generated by Django 2.0.5 on 2019-04-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0009_fcsettings_extract_sentences'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcsettings',
            name='lessons_rand_old',
            field=models.IntegerField(default=20),
        ),
    ]
