# Generated by Django 2.0.5 on 2019-04-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0010_fcsettings_lessons_rand_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcsettings',
            name='lessons_rand_old',
        ),
    ]
