# Generated by Django 2.0.5 on 2019-04-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0011_remove_fcsettings_lessons_rand_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcsettings',
            name='lessons_rand_old',
            field=models.IntegerField(default=60),
        ),
    ]
