# Generated by Django 2.0.5 on 2019-06-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0012_fcsettings_lessons_rand_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcsettings',
            name='randomize',
            field=models.BooleanField(default=True),
        ),
    ]
