# Generated by Django 2.0.5 on 2019-06-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0013_fcsettings_randomize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcsettings',
            name='chunk_size',
        ),
    ]
