# Generated by Django 2.0.5 on 2019-06-08 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcards', '0014_remove_fcsettings_chunk_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedInPast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma_ID', models.CharField(max_length=50)),
                ('times_processed', models.IntegerField()),
                ('project_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='processedInPast', to='fcards.Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processedInPast', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
