# Generated by Django 2.0.5 on 2019-06-08 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcards', '0015_processedinpast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedinpast',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='processedinpast',
            name='user_id',
        ),
        migrations.AddField(
            model_name='processedinpast',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='processed_in_past', to='fcards.Project'),
        ),
        migrations.AddField(
            model_name='processedinpast',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='processed_in_past', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processedinpast',
            name='times_processed',
            field=models.IntegerField(default=1),
        ),
    ]
