# Generated by Django 2.0.5 on 2018-09-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcards', '0005_auto_20180909_2131'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytextfilesmodel',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='text_files', to='fcards.Project'),
        ),
    ]
