# Generated by Django 2.0.5 on 2019-04-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_mytextfilesmodel_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytextfilesmodel',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
